### ISSUE TITLE
There is no parameters logging feature on Laravel 10.

### ISSUE THREAD

**Issue by memiljamel** [bilfeldt/laravel-route-statistics#41]
Hi, this is a great package for logging requests. But why when I install this package there is no parameters feature? So I want to use laravel's `route()` helper to translate the route name stored in the database, but there are cases where a route requires parameters.

In other words, the source code downloaded by composer is not the same as the one in the github repository, there is no parameters logging feature.

I am using version 3.20 on Laravel 10

**Comment by bilfeldt** [comment]
You are completelt right, I can see that I completely forgot to release this new awesome feature: https://github.com/bilfeldt/laravel-route-statistics/pull/39#issuecomment-2234295159

Simple require `dev-master` instead of version 3.20 while I write an upgrade guide for this. If you wanna write an upgrade guide for this, feel free to submit a PR then I will tag the new version.

**Comment by bilfeldt** [comment]
Released https://github.com/bilfeldt/laravel-route-statistics/releases/tag/v4.0.0
